services:
  yugabyte1:
    image: yugabytedb/yugabyte:2.21.0.0-b545
    container_name: yugabyte1
    command: ["bin/yugabyted", "start", "--daemon=false"]
    ports:
      - "7000:7000"
      - "7100:7100"
      - "9000:9000"
      - "9042:9042"
      - "5433:5433"
      - "6379:6379"
    networks:
      - yugabyte-network

networks:
  yugabyte-network:
    driver: bridge