services:
  yugabyte2:
    image: yugabytedb/yugabyte:2.21.0.0-b545
    container_name: yugabyte2
    command: ["bin/yugabyted", "start", "--daemon=false", "--join=192.168.56.104"] # IP of Node 1
    network_mode: "host"
    restart: unless-stopped