services:
  yugabyte1:
    image: yugabytedb/yugabyte:2.21.0.0-b545
    container_name: yugabyte1
    command: ["bin/yugabyted", "start", "--daemon=false", "--rpc_bind_addresses=192.168.1.101:7100", "--server_broadcast_addresses=192.168.1.101:7100", "--webserver_interface=192.168.1.101", "--tserver_master_addrs=192.168.1.101:7100"]
    network_mode: "host"
    restart: unless-stopped