services:
  yugabyte1:
    image: yugabytedb/yugabyte:2.21.0.0-b545
    container_name: yugabyte1
    command: ["bin/yugabyted", "start", "--daemon=false"]
  
  yugabyte2:
    image: yugabytedb/yugabyte:2.21.0.0-b545
    container_name: yugabyte2    
    command: ["bin/yugabyted", "start", "--daemon=false", "--join=yugabyte1"]
    restart: on-failure:10

  yugabyte3:
    image: yugabytedb/yugabyte:2.21.0.0-b545
    container_name: yugabyte3
    command: ["bin/yugabyted", "start", "--daemon=false", "--join=yugabyte1"]
    restart: on-failure:10

  yugabyte-init:
    image: yugabytedb/yugabyte:2.20.1.3-b3
    container_name: yugabyte-init
    depends_on:
      - yugabyte1
      - yugabyte2
      - yugabyte3
    entrypoint: /bin/sh
    command: -c "sleep 20 && /home/yugabyte/bin/ysqlsh --echo-queries --host yugabyte1 -U postgres -d postgres -c 'CREATE DATABASE data;'"