version: "3.8"

services:
  gql_workflow:
    image: gql_workflow
    build:
      # context definuje cestu k popisu
      context: ./gql_workflows
    environment:
      # promenne, ktere lze cist v kontejneru
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_DB=data
      - DEMO=true
    restart: on-failure:3 # nedojde k restartu pokud je kontejner "unhealthy", maximalne 3 pokusy
    ports: #v deploymentu by nebylo zadne mapovani portu
    #   # vnejsi port : port, kde sluzbu poskytuje kontejner
      - 31123:8000