version: "3.8"

services:
  postgres:
    container_name: postgres_single
    image: "postgres:16.0"
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data
    ports:
      - "5432:5432"

