version: "3.8"


############### yugabyte volumes ###############
volumes:
  yb-master-data-1:
  yb-tserver-data-1:


services:

  ########### pgadmin ################
  pgadmin:
    container_name: pgadmin4
    image: "dpage/pgadmin4:7.7"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  

  ############ postgres ################
  postgres:
    container_name: postgres_single
    image: "postgres:16.0"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data
    ports:
      - "5432:5432"


  ############## yugabyte ######################
  yb-master:
      image: yugabytedb/yugabyte:2.19.2.0-b121
      container_name: yb-master-n1
      volumes:
      - yb-master-data-1:/mnt/master
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master-n1:7100",
                "--rpc_bind_addresses=yb-master-n1:7100",
                "--replication_factor=1"]
      ports:
      - "7000:7000"
      environment:
        SERVICE_7000_NAME: yb-master

  yb-tserver:
      image: yugabytedb/yugabyte:2.19.2.0-b121
      container_name: yb-tserver-n1
      volumes:
      - yb-tserver-data-1:/mnt/tserver
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=yb-tserver-n1:9100",
                "--tserver_master_addrs=yb-master-n1:7100"
                ]
      ports:
      - "9042:9042"
      - "5433:5433"
      - "9001:9000"
      environment:
        SERVICE_5433_NAME: ysql
        SERVICE_9042_NAME: ycql
        SERVICE_6379_NAME: yedis
        SERVICE_9000_NAME: yb-tserver
        POSTGRES_USER: root
      depends_on:
      - yb-master

  yb-client:
      image: yugabytedb/yb-sample-apps:1.3.9
      container_name: yb-client-n1
      command: [ "--workload", "SqlInserts", "--nodes", "yb-tserver-n1:5433" ]
      depends_on:
      - yb-tserver


