version: '3.8'

# volumes:
#   yb-master-data-1:
#   yb-tserver-data-1:

# networks:
#   roachnet:
#     driver: bridge

services:

  ########### pgadmin ################
  pgadmin:
    container_name: pgadmin4
    image: "dpage/pgadmin4:7.8"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


  ############## yugabyte ######################
  yugabyte:
    image: yugabytedb/yugabyte:2.19.3.0-b140
    container_name: yugabyte
    ports:
      - "7000:7000"
      - "9001:9000"   # rebind because of portainer
      - "15433:15433" # cluster GUI
      - "5433:5433"
      - "9042:9042"

    # networks:
    #   - yb_network
    
    command: ["bin/yugabyted", "start", "--daemon=false"]