services:
  pgadmin:
    container_name: pgadmin4
    image: "dpage/pgadmin4:7.8"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    network_mode: "host"

  postgres:
    container_name: postgres
    image: "postgres:16.0"
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data
    network_mode: "host"

  apollo:
    image: hrbolek/apollo_federation:latest
    container_name: apollo
    environment:
      PORT: 3000
      SERVICES: '[{"name": "ug", "url": "http://gql_ug:8000/gql"}]'
    healthcheck:
      interval: 60s
      retries: 3
      start_period: 60s
      timeout: 10s
    restart: on-failure
    depends_on:
      - postgres
    network_mode: "host"

  frontend:
    image: hrbolek/frontend
    container_name: frontend
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_DB: data
      SALT: fe1c71b2-74c0-41e5-978f-eecbffac7418
      DEMO: "False"
      GQL_PROXY: http://apollo:3000/api/gql/
    network_mode: "host"
    depends_on:
      apollo:
        condition: service_started
